### PR TITLE
Update rebar.config

### PR DESCRIPTION
**Pull request by ruanpienaar**
Hi Krzysztof

the empty list erlang options prevents rebar from crashing on compilation. Could you add it to rebar.config.

The below happens, if eenum does NOT have : {erl_opts, []}.

rpmbp:of_protocol ruanpienaar$ make
==> of_protocol (get-deps)
Pulling eenum from {git,"git://github.com/rpt/eenum.git",{branch,"master"}}
Cloning into 'eenum'...
Pulling meck from {git,"https://github.com/eproxus/meck.git",{tag,"0.8.2"}}
Cloning into 'meck'...
==> eenum (get-deps)
==> meck (get-deps)
==> eenum (compile)
/Users/ruanpienaar/code/of_protocol/deps/eenum/src/eenum.erl:none: undefined parse transform 'eenum'
ERROR: compile failed while processing /Users/ruanpienaar/code/of_protocol/deps/eenum: rebar_abort
make: **\* [compile] Error 1

### CODE REVIEW

**Comment by rpt** [comment]
@ruanpienaar Looks like a bug in rebar, what version of rebar are you using?

**Comment by ruanpienaar** [comment]
Built my rebar from branch develop.

**Comment by rpt** [comment]
@ruanpienaar As I said, it's a rebar issue, nothing to do with this repo.

**Comment by ruanpienaar** [comment]
Yeah, sure. i'll log a ticket with rebar.
But in the interim, i'll just use my fork, until rebar fixes it.
Thanks

**Pull request closed without merging**
